### ISSUE TITLE
Admin Password in Docker Compose

### ISSUE THREAD

**Issue by Chacsam** [spiral-project/ihatemoney#1169]
Hello,

I am trying to install ihatemoney through a Portainer Stack (docker-compose file), but I cannot get the Admin password to work..
Using a https reverse proxy I avoid the invalid CRSF with secure cookies, but I always get "Admin password: This admin password is not the right one. Only x attempts left." on the admin page.

My code to generate the hash: `docker run -it --rm --entrypoint ihatemoney ihatemoney/ihatemoney generate_password_hash`

My Docker-compose
```
version: "3.0"
services:
  ihatemoney:
    image: ihatemoney/ihatemoney:latest
    container_name: I_Hate_Money
    network_mode: "bridge"
    environment:
      - BABEL_DEFAULT_TIMEZONE=xxx
      - ACTIVATE_ADMIN_DASHBOARD=True
      - ACTIVATE_DEMO_PROJECT=False
      - ALLOW_PUBLIC_PROJECT_CREATION=True
      - SHOW_ADMIN_EMAIL=True
      - ADMIN_PASSWORD=pbkdf2:sha256:260000$bvN2imsPpC323VGJ$xxxxxx
      - MAIL_SERVER=xxx
      - MAIL_PORT=587
      - MAIL_DEFAULT_SENDER=Expense Split <xxxxx@xxxxx.xx>
      - MAIL_USERNAME=xxxx@xxx.xx
      - MAIL_PASSWORD=xxxx
      - MAIL_USE_SSL=False
      - MAIL_USE_TLS=True
    volumes:
      - /home/my_map/apps/ihatemoney/db:/database
    ports:
      - 41008:8000
    restart: unless-stopped
```
Docker 24.0 on a Ubuntu 22.04 container in Proxmox.

Am I doing something wrong?
