### ISSUE TITLE
docker-compose production setup

### ISSUE THREAD

**Issue by mcnesium** [spiral-project/ihatemoney#332]
I keep failing to run this project in a productive Docker environment. Several attempts to go [after the documentation](https://ihatemoney.readthedocs.io/en/latest/installation.html#with-docker) failed because the config file kept being overwritten by the default values from either [here](https://github.com/spiral-project/ihatemoney/blob/master/conf/confandrun.sh#L2) or [here](https://github.com/spiral-project/ihatemoney/blob/master/Dockerfile#L14). Also that #322 issue…

So I tried to set up a streamlined environment with the following configuration files:

`./docker-compose.yml`:
```yaml
version: '3'

services:
  mariadb:
    image: mariadb
    restart: always
    volumes:
      - /srv/ihatemoney/database:/var/lib/mysql
  app:
    build: ./
    restart: always
    links:
      - mariadb:mariadb
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - /etc/ihatemoney:/etc/ihatemoney
```

`./Dockerfile`:
```Dockerfile
FROM python:3.6-alpine

RUN pip install --no-cache-dir gunicorn pymysql &&\
    pip install --no-cache-dir ihatemoney

EXPOSE 8000
ENTRYPOINT ["/etc/ihatemoney/confandrun.sh"]
```
`/etc/ihatemoney/confandrun.sh`:
```sh

#!/bin/sh
exec gunicorn ihatemoney.wsgi:application \
     -b 0.0.0.0:8000 \
     --log-syslog \
     "$@"
```
`/etc/ihatemoney/ihatemoney.cfg`:
```
DEBUG = False
SQLALCHEMY_DATABASE_URI = "mysql+pymysql://ihatemoney:xxxxxxxxxxxxxxxx@mariadb"
SQLACHEMY_DEBUG = DEBUG
SQLALCHEMY_TRACK_MODIFICATIONS = False
SECRET_KEY = "xxxxxxxxxxxxxxxx"
MAIL_SERVER = "mail.domain.de"
MAIL_PORT = 587
MAIL_USE_TLS = True
MAIL_USE_SSL = True
MAIL_USERNAME = "uuuuuuuu"
MAIL_PASSWORD = "xxxxxxxxxxxxxxxx"
MAIL_DEFAULT_SENDER = "('ihatemoney', 'manager@ihatemoney.domain.de')"
ACTIVATE_DEMO_PROJECT = True
ADMIN_PASSWORD = "xxxxxxxxxxxxxxxx"
ALLOW_PUBLIC_PROJECT_CREATION = True
ACTIVATE_ADMIN_DASHBOARD = True
```

This way the app container keeps trying to restart stating `sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1046, 'No database selected')` in the logs.

So what is the problem here? Why does it not use the `SQLALCHEMY_DATABASE_URI` configuration?

**Comment by almet** [comment]
Hi, I'm sorry I can't really help you out on this, as I don't run docker myself. Maybe @0livd or @pR0Ps can help you on this one?

**Comment by indatwood** [comment]
Hi, is there anybody around here with expertise on docker?

**Comment by jdckr** [comment]
Hi,

I didn't have any problems deploying it with docker. I basically followed the available documentation.
I built the image with:
`docker build -t ihatemoney:local .`

After that I deployed it with docker-compose:
``` yaml
version: '3'
services:
  ihatemoney:
    container_name: ihatemoney
    volumes:
      - </path/to/database/folder>:/database
    image: ihatemoney:local
    ports:
      - <host-port>:8000
    environment:
      - MAIL_SERVER=<value>
      - MAIL_PORT=<value>
      - MAIL_USERNAME=<value>
      - MAIL_PASSWORD=<value>
      - MAIL_USE_TLS=<value>
      - MAIL_DEFAULT_SENDER=<value>
      - ACTIVATE_DEMO_PROJECT=False
      - ADMIN_PASSWORD=<value>
      - ALLOW_PUBLIC_PROJECT_CREATION=True
      - ACTIVATE_ADMIN_DASHBOARD=True
      - NIGHTLY=True
    restart: unless-stopped
```

 [entrypoint.sh](https://github.com/spiral-project/ihatemoney/blob/master/conf/entrypoint.sh) lists the available environment variables which are used to create the config file.

The container must only be build once. The newest version from PyPI or GitHub (NIGHTLY=False or NIGHTLY=True) is installed upon container restart.

As entrypoint.sh also creates the config file, external changes will be overwritten. A workaround is to adapt entrypoint.sh before building the image in order to deactivate config creation.
